version: '3'
services:
    db:
        image: mariadb:10.3.7
        volumes:
            - db-volume:/var/lib/mysql
            #- ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database
            MYSQL_USER: admin
            MYSQL_PASSWORD: insecure
        ports:
            - "3306:3306"
    api:
        build: backend
        volumes:
            - ./backend/src:/var/www/html
            - ./backend/.git:/var/www/html/.git
            - webpack-build:/var/www/html/redux
    webclient:
        build: frontend
        user: ${UID}
        environment:
            - "REACT_APP_ENVIRONMENT=development"
            - "REACT_APP_API_BASE_URL=https://localhost/api/v1/"
            - "REACT_APP_MODULES_BASE_URL=https://localhost/modules/"
            - "PUBLIC_URL=https://localhost/redux/"
        volumes:
            - ./frontend:/dagger
            - webpack-build:/dagger/build
            - node-modules:/dagger/node_modules
        ports:
            - "3000:3000"
    haproxy:
        image: haproxy:1.8-alpine
        volumes:
            - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
            - ./bundle.pem:/etc/ssl/xip.io/xip.io.pem
        ports:
            - "80:80"
            - "443:443"
volumes:
    db-volume:
    webpack-build:
    node-modules:
