version: '3'
services:
    webclient:
        build: .
        user: ${UID}
        environment:
            - "REACT_APP_ENVIRONMENT=production"
            - "PUBLIC_URL=https://www.mlaga97.space/seconsim2019/"
        volumes:
            - ./:/dagger
            - webpack-build:/dagger/build
            - node-modules:/dagger/node_modules
        ports:
            - "3000:3000"
volumes:
    webpack-build:
    node-modules:
